package People.Employee;

import People.Person;

public abstract class Employee implements Person {
   private String firstName;
   private String lastName;

   public String jobTitle;

    //generated by the DB
    private int employeeId;


    public Employee(String firstName, String lastName) {
        firstName = firstName;
        lastName = lastName;
    }

    public String fullName() {
        String fullName = firstName + lastName;
        return fullName;
    }

    public int getId() {
        return employeeId;
    }

    public void setId(int id) {
        this.employeeId = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        firstName = firstName;
    }
    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        lastName = lastName;
    }

    @Override
    public String toString() {
        return "Employee{" +
                "firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                '}';
    }
}
